dataset_path: /share/minghao/Datasets/VideoDatasets/VNBench_dataset
dataset_kwargs:
  token: True
  cache_dir: VNBench_new
  video: True
  load_from_disk: True
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
task: vnbench
test_split: test
output_type: generate_until
doc_to_visual: !function utils.vnbench_doc_to_visual
doc_to_text: !function utils.vnbench_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.vnbench_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: vnbench_perception_score
    aggregation: !function utils.vnbench_aggregate_results
    higher_is_better: true